import "./globals.css";
import Link from "next/link"; //this component works as a <a> and redirects to a new page

export const metadata = {
  title: 'SpotifyReviews',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className=" container flex  justify-between bg-slate-400">{//create a navbar to set the logo and menu
        }<span>
            
            <p>SpotifyReviews</p>
            </span>
            <ol className="container flex  justify-end gap-2">
              <Link href={"/reviews"}>Reviews</Link>
              <Link href={"/"}>Home</Link>
              <Link href={"/songs"}>Songs</Link>
              <Link href={"/about-us"}>About Us</Link>
            </ol>
        </nav>
        {children}
      </body>
    </html>
  )
}
